name: Deploy PHP App to Azure App Service using UAMI + OIDC

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy-uat:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to UAT slot
      uses: azure/webapps-deploy@v3
      with:
        app-name: php-webapp-prod
        slot-name: php-webapp-prod-uat
        scm-do-build-during-deployment: true
      env:
        AZURE_CLIENT_ID: b04abe34-d3e1-4a15-9960-00bf52c3d692
        AZURE_TENANT_ID: 7cb9246c-9ffa-4869-960b-f0e8772aef84
        AZURE_SUBSCRIPTION_ID: 45fdcc40-c3eb-4c95-abb1-6f7ce0145829

  deploy-prod:
    runs-on: ubuntu-latest
    needs: deploy-uat
